services:
  smard-probabilistic:
    build: .
    environment:
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: none
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_BROWSER_SERVER_ADDRESS: localhost
      STREAMLIT_BROWSER_SERVER_PORT: "8503"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
      MPLBACKEND: Agg
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      PYTORCH_NUM_THREADS: "1"
    ports:
      - "8503:8501"
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
